FROM nginx:latest

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=/ST=/L=/O=/CN=name" -keyout /etc/ssl/private/dev.key  -out /etc/ssl/certs/dev.cert

COPY ./default.conf /etc/nginx/conf.d/default.conf
